Improve Map Accessibility with Local Language Translations and Set Max Zoom Level
hackclub/map pull request #12
Opened 2024-11-08 06:34 UTC by hashim-baloch

This pull request enhances the user experience and accessibility of the map by:

## Adding Tile Layer with Local Translations:

Replaced the previous tile layer with one that includes translations for local scripts, especially in regions like China, Afghanistan, and Pakistan. This resolves the issue of untranslated labels that made navigation challenging for users unfamiliar with certain scripts.
## Setting Maximum Zoom-Out Level:

Added a maximum zoom level to prevent excessive zooming out, ensuring the map view remains within practical bounds for better usability.
## Issue Resolved:
- #11 

# Screenshots:
# Before: 
![image](https://github.com/user-attachments/assets/7c3dc6ce-bccc-4f3c-b3a9-40e3d7bb8a0c)
![image](https://github.com/user-attachments/assets/313f74f2-e875-432c-baa3-8d16797d8e32)
![image](https://github.com/user-attachments/assets/29eb5025-ff9b-4011-8a48-eac4a069c6af)

# After: 
English translation with local languages
![image](https://github.com/user-attachments/assets/b21d128f-2a15-4c41-8a29-24c4664d4869)
max-zoom level
![image](https://github.com/user-attachments/assets/f1217d32-fc8d-41e0-9d15-d6dd263a6dd5)
max-zoom

2024-12-22 11:02 UTC, JosiasAurel requested changes

2024-12-22 11:02 UTC, JosiasAurel commented on club-map.js
> +      [90, 180], // Northeast corner of the bounding box
why this addition?

2024-12-22 11:02 UTC, JosiasAurel commented on club-map.js
> +  L.tileLayer("https://tile.openstreetmap.de/{z}/{x}/{y}.png", {
what does the change on this line do?

2024-12-22 11:06 UTC, hashim-baloch commented on club-map.js
> +      [90, 180], // Northeast corner of the bounding box
It is used to set/restrict the viewable area of the map, ensuring users can only pan within the specified geographic bounds.

2024-12-22 11:07 UTC, hashim-baloch commented on club-map.js
> +  L.tileLayer("https://tile.openstreetmap.de/{z}/{x}/{y}.png", {
It is used to set the tile layer. The one which contains the translations for non-english scriptures.

2024-12-22 11:14 UTC, hashim-baloch commented
Do you still want me to un-format the changes?

2024-12-23 08:05 UTC, JosiasAurel approved these changes
lgtm

2024-12-24 07:28 UTC, merged